DROP VIEW IF EXISTS EasyTests;
DROP TABLE IF EXISTS Tests;
DROP TABLE IF EXISTS Isolates;
DROP TABLE IF EXISTS Microbes;
DROP TABLE IF EXISTS Breakpoints;
DROP TABLE IF EXISTS Drugs;
DROP TABLE IF EXISTS Samples;


CREATE TABLE Samples
(
	ID VARCHAR(15) NOT NULL PRIMARY KEY,
	Year INT,
	State VARCHAR(15),
	MeatType VARCHAR(15),
	Organic BOOLEAN,
	Agency VARCHAR(15),
	Source VARCHAR(15),
	HostSpecies VARCHAR(15)
);

CREATE TABLE Microbes
(
	ID INT NOT NULL PRIMARY KEY,
	Genus VARCHAR(5),
	Species VARCHAR(25),
	Serotype VARCHAR(25),
	AntigenicFormula VARCHAR(25)
);

CREATE TABLE Isolates
(
	ID VARCHAR(15) NOT NULL PRIMARY KEY,
	SampleID VARCHAR(15),
	MicrobeID INT,
	CONSTRAINT Isolates_Samples_ID_fk FOREIGN KEY(SampleID) REFERENCES Samples (ID),
	CONSTRAINT Isolates_Microbes_ID_fk FOREIGN KEY(MicrobeID) REFERENCES Microbes (ID)
);

CREATE TABLE Drugs
(
	ID VARCHAR(3) NOT NULL PRIMARY KEY,
	Name VARCHAR(15),
	Type VARCHAR(15),
	TypeName VARCHAR(25),
	Family VARCHAR(10),
	FamilyName VARCHAR(25),
	Class VARCHAR(10),
	ClassName VARCHAR(25)
);

CREATE TABLE Breakpoints
(
	DrugID VARCHAR(3),
	Genus VARCHER(5),
	MICI DEC(8,3),
	MICR DEC(8,3),
	CONSTRAINT Breakpoints_Drugs_ID_fk FOREIGN KEY(DrugID) REFERENCES Drugs (ID),
	CONSTRAINT Breakpoints_Microbes_Genus_fk FOREIGN KEY(Genus) REFERENCES Microbes (Genus)
);

CREATE TABLE Tests
(
	IsolateID VARCHAR(15),
	DrugID VARCHER(3),
	MIC DEC(8,4),
	CorrectedMIC DEC(8,4),
	Sign CHAR(2),
	PRIMARY KEY (IsolateID, DrugID),
	CONSTRAINT Tests_Drugs_ID_fk FOREIGN KEY(DrugID) REFERENCES Drugs (ID),
	CONSTRAINT Tests_Isolates_ID_fk FOREIGN KEY(IsolateID) REFERENCES Isolates (ID)
);

























